# Generated by Django 5.2.4 on 2025-10-14 03:52

from django.db import migrations


def create_weekdays(apps,schema_editor):
        Day=apps.get_model('time','Day') # pylint: disable=no-member
        days=["Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo"]
        for day_name in days:
            Day.objects.create(name=day_name)

def delete_weekdays(apps, schema_editor):
    WeekDay = apps.get_model('time', 'Day')
    db_alias = schema_editor.connection.alias

    # Borrar todos los registros
    WeekDay.objects.using(db_alias).all().delete()

    # Resetear la secuencia del ID a 1
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER SEQUENCE time_day_id_seq RESTART WITH 1;")

def create_cycles(apps,schema_editor):
        Cycle=apps.get_model('time','Cycle')
        periods=['1','2']
        years=[2023,2024,2025]

        for year in years:
            for period in periods:
                Cycle.objects.create(name=f'{year}-{period}',year=year,number=period)

def delete_cycles(apps, schema_editor):
    Cycle = apps.get_model('time', 'Cycle')
    db_alias = schema_editor.connection.alias

    # Borrar todos los registros
    Cycle.objects.using(db_alias).all().delete()

    # Resetear la secuencia del ID a 1
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER SEQUENCE time_cycle_id_seq RESTART WITH 1;")

class Migration(migrations.Migration):

        dependencies = [
            ('time', '0001_initial'),
        ]

        operations = [
            migrations.RunPython(create_weekdays,delete_weekdays),
            migrations.RunPython(create_cycles,delete_cycles)
        ]
