FROM node:22.18.0-slim

RUN npm install -g @angular/cli@20

WORKDIR /angular_frontend

COPY ./Angular_frontend .

RUN npm install --no-audit --no-fund --legacy-peer-deps


EXPOSE 4200

CMD ["ng","serve","--host","0.0.0.0"]