
services:
  bd_postgres:
    image: postgres:14.18
    ports:
      - "5433:5432"
    volumes:
      - bd_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.development
    # environment:
    #   -POSTGRES_USER=${USER_POSTGRES}
    #   -POSTGRES_PASSWORD=${PASSWORD_POSTGRES}
    #   -POSTGRES_DB=${DB_POSTGRES}
    healthcheck:
      test: "pg_isready -U BDFL -d CRM"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm_network

  service_crm:
    container_name: CRM_Django
    ports:
      - "8001:8000"
    build:
      context: ./CRM_Django
      dockerfile: DockerFile
    # environment:
    #   - DB_HOST=bd_postgres
    #   - DB_PORT=${CONTAINER_PORT_DB}
    #   - DB_NAME=${NAME_DB}
    #   - DB_USER=${USER_DB}
    #   - DB_PASSWORD=${PASSWORD_DB}
    env_file:
      - ./.env.development
    depends_on:
      bd_postgres:
        condition: service_healthy
    volumes:
      - ./CRM_Django:/crm_django
    networks:
      - crm_network
      - service_network
  
  nlp_service:
    container_name: NLP_Service
    build:
      context: ./NLP_Service
      dockerfile: DockerFile
    ports:
      - "6001:6000"
    # environment:
    #   - HOST_CRM=${HOST_CRM}
    env_file:
      - .env.development
    depends_on:
      - service_crm
    volumes:
      - ./NLP_Service:/nlp_service
    networks:
      - service_network
  frontend:
    container_name: Angular_frontend
    build:
      context: ./Frontend
      dockerfile: DockerFile
    ports:
      - "4201:4200"
    # environment:
    #   - API_URL=${API_URL}
    env_file:
      - ./.env.development
    depends_on:
      - service_crm
    volumes:
      - ./Frontend/Angular_frontend:/angular_frontend
    networks:
      - service_network
volumes:
  bd_postgres_data:
    driver: local
  crm_django:
    driver: local
  nlp_service:
    driver: local
  angular_frontend:
    driver: local
networks:
  crm_network:
    driver: bridge
  service_network:
    driver: bridge
