# Generated by Django 5.2.4 on 2025-10-14 04:24

from django.db import migrations


def create_services(apps,schema_editor):
    Services=apps.get_model('services','Service') # pylint: disable=no-member
    services=['Comedor','Gimnasio','Biblioteca','Clinica']
    for service in services:
        Services.objects.create(name=service)

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
                  migrations.RunPython(create_services)
    ]
