# Generated by Django 5.2.4 on 2025-10-20 05:10

from django.db import migrations
from django.contrib.auth.hashers import make_password



class Migration(migrations.Migration):

    def add_roles(apps,schema_editor):
        Role=apps.get_model('authentication','Role')
        Role.objects.create(name="Bienestar",description="Personal del area de bienestar universitario")

    def add_user(apps,schema_editor):
        User=apps.get_model('authentication','User')
        Role = apps.get_model('authentication', 'Role')

        bienestar_role = Role.objects.get(name="Bienestar")
        User.objects.create(username="Ames",password=make_password('admin123'),role_id=bienestar_role.id)

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles),
        migrations.RunPython(add_user)
    ]
