FROM node:22.18.0-slim

RUN npm install -g @angular/cli@20

WORKDIR /angular_frontend

#Hacer un volumen para node_modules
COPY . .
RUN npm install --no-audit --no-fund --legacy-peer-deps

CMD ["ng","serve"]